# Generated by Django 5.0.6 on 2024-07-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='git_link',
            field=models.CharField(default='fghyj', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='netlify_link',
            field=models.CharField(default='iklo', max_length=1000),
        ),
    ]
